### ISSUE TITLE
Number of spectral mixtures

### ISSUE THREAD

**Issue by imsrgadich** [gparracl/MOSM#1]
I just skimmed through the project, I see that there no option for `number of spectral components`.

I was wondering because I myself am implementing SM kernel with more mixture components, I'm running into Cholesky decomposition problems. I was just here to see how that was taken care of here. thank you.

if I've missed something my apologies.

**Comment by gparracl** [comment]
I consider a SM kernel of N spectral components as the sum of N SM kernels of 1 spectral component, so i just sum the kernels using GPflow kernel class operations.

**Comment by imsrgadich** [comment]
you mean here? 
```
#Set the number of components
number_of_components = 2
kern = MOSM(INPUT_DIM, N_OUTPUTS)
for i in range(number_of_components-1):
        kern += MOSM(INPUT_DIM, N_OUTPUTS)
```

Have you run into any Cholesky problems? if so, how have you dealt with that?

**Comment by gparracl** [comment]
yes, there.
With this particular kernel I havent run into Cholesky problems but usually the noise parameter helps you with that by pushing the eigen values of the kernel matrix to being positive.

**Comment by imsrgadich** [comment]
I guess I need to follow your strategy and add up the kernels. Thank you.
Any other trick you followed with this kernel? Anything specific?

**Comment by gparracl** [comment]
Initialization can be tricky with spectral kernels in general, specially with a large number of spectral components, if you dont want to go down the MCMC road, you can try looking at the DFT of your data and fit a sum of gaussians there and use those parameters (means, variances and weights) as initialization. This is what A. Wilson did in his thesis and apparently works fairly well.

**Comment by imsrgadich** [comment]
Thank you. I will look into his thesis. Appreciate it. 
On 18 Apr 2018 4:14 AM, gparracl <notifications@github.com> wrote:Initialization can be tricky with spectral kernels in general, specially with a large number of spectral components, if you dont want to go down the MCMC road, you can try looking at the DFT of your data and fit a sum of gaussians there and use those parameters (means, variances and weights) as initialization. This is what A. Wilson did in his thesis and apparently works fairly well.

**Comment by imsrgadich** [comment]
the error in my code was that I didn't constraint spectral mixture weights to be positive. after doing that the code worked.
